sx_blog/__init__.py
from logging import DEBUG

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from sx_blog.model import db
from sx_blog.controllers import blog, backstage_management

app = Flask(__name__)
app.secret_key = 'zzj'
app.config[DEBUG] = True

app.register_blueprint(blog.bg)
app.register_blueprint(backstage_management.bm)
app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://root:123456@114.215.196.6:3306/sx_onepiece_blog?charset=utf8'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db.init_app(app)

# from sx_blog.controllers  import blog
from sx_blog import commands, model

sx_blog/controllers/backstage_management.py
import datetime

from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for, jsonify
)
from sx_blog.model import db, user, Blog, blog_type

bm = Blueprint('backstage', __name__, url_prefix='/backstage')


@bm.route('login', methods=['POST', 'GET'])
def login():
    return render_template("login_register.html")


@bm.route("ta_login", methods=["post"])
def ta_login():
    '''这是个登录功能'''
    print("success")
    uname = request.form.get("l_uname", "")
    upwd = request.form.get("l_upwd", "")
    # print(request.form.__str__())
    a = user.query.filter(user.username == uname, user.password == upwd).all()
    print(a)
    if len(a) == 0:
        return "0"
    else:
        return "1"


@bm.route("manager", methods=["post", "get"])
def manager():
    return render_template("admin.html")


@bm.route("articleList", methods=['POST', 'GET'])
def articleList():
    return render_template("articleList.html")


@bm.route("/findArticleList")
def findArticleList():
    limit = request.args.get("limit")
    page = request.args.get("page")
    rs = Blog.query.all()
    data = []
    for i in rs:
        d = {}
        d['id'] = i.id
        d['title'] = i.title
        d['describe'] = i.describe
        d['creation_time'] = i.creation_time
        type = blog_type.query.get(i.type_id).name
        d['type'] = type
        data.append(d)
    # print(data)
    return jsonify({'count': len(data), 'data': data[int(page) - 1:(int(page) + int(limit))], 'code': 0})


@bm.route("articleAdd", methods=['POST', 'GET'])
def articleAdd():
    a = blog_type.query.all()
    return render_template("articleAdd.html", type=a)


@bm.route("Addarticle", methods=['POST', 'GET'])
def Addarticle():
    text = request.form.get("text")
    type = request.form.get("type")
    title = request.form.get("title")
    print(title)
    describe = request.form.get("describe")
    now = datetime.datetime.now()
    temp = Blog(content=text, type_id=type, title=title, describe=describe, creation_time=now, views_number=0,
                user_id=1)
    db.session.add(temp)
    db.session.commit()
    return "success"


@bm.route("typeList", methods=['POST', 'GET'])
def typeList():
    return render_template("typeList.html")


@bm.route("/findTypeList")
def findTypeList():
    limit = request.args.get("limit")
    page = request.args.get("page")
    rs = blog_type.query.all()
    data = []
    for i in rs:
        d = {}
        d['id'] = i.id
        d['name'] = i.name
        data.append(d)
    print(data)
    return jsonify({'count': len(data), 'data': data[int(page) - 1:(int(page) + int(limit))], 'code': 0})


@bm.route("welcome", methods=['POST', 'GET'])
def welcome():
    return render_template("welcome.html")


@bm.route("/getUnivTagsDataForPie")
def getUnivTagsDataForPie():
    a = Blog.query.limit(4).all()
    list = []
    for item in a:
        dict = {}
        dict["name"] = item.title
        dict["value"] = item.views_number
        list.append(dict)
    print(list)
    return jsonify(list)


@bm.route("/deleteUnivById", methods=["post"])
def deleteUnivById():
    id = request.form.get("id")
    b = Blog.query.get(id)
    db.session.delete(b)
    db.session.commit()
    print("success")
    return "1"
# @bm.route("/login",methods=["post"])
# def login():
#   '''这是个登录功能'''
#  uname=request.form.get("l_uname","")
# upwd=request.form.get("l_upwd","")
# print(request.form.__str__())


# conn=MySQLHelper();
# sql="select * from tb_user where uname=%s and upwd=md5(%s)"
# rs=conn.executeForSelectAll(sql,(uname,upwd))
# i=rs.__len__()
# print(i)
# if i==0:
#     return "0"#同步请求 fault
# else:
#     return "1"  # success

sx_blog/controllers/blog.py
import json

from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for, jsonify
)
# from flask_pagedown import PageDown
from sx_blog.model import Blog, db, blog_type
from sx_blog.SpeakModel import *

bg = Blueprint('blog', __name__, url_prefix='/blog')


@bg.route("/", methods=('GET', 'POST'))
def index():
    bg = Blog.query.all()
    zxbg = Blog.query.limit(4).all()
    # zxbg = Blog.query.all()
    return render_template("index.html", zxblog=zxbg, blog=bg)


@bg.route("/blogpage/<blog_id>", methods=('GET', 'POST'))
def blogpage(blog_id):
    print(blog_id)
    blog_id = a= int(blog_id)
    bg = Blog.query.get(blog_id)
    type = blog_type.query.get(bg.type_id)
    return render_template("blog.html", bg=bg, type=type.name)


@bg.route("/blogpage/content", methods=('GET', 'POST'))
def content():
    data = request.form.get('url')
    data = data.split('/')
    id = int(data[len(data) - 1])
    # print(id)
    bg = Blog.query.get(id)
    # dist = {}
    # print(bg.content)
    return bg.content


@bg.route("/type", methods=('GET', 'POST'))
def type():
    ty = blog_type.query.all()
    zxty = blog_type.query.limit(4).all()
    return render_template("types.html", zxtype=zxty, type=ty)




@bg.route("/markdown", methods=('GET', 'POST'))
def markdown():
    return render_template("markdown.html")


@bg.route("/biaodan", methods=('GET', 'POST'))
def biaodan():
    bg = Blog.query.first()
    # val = request.form.get("edi")
    text = request.form.get("text")
    bg.content = text
    db.session.commit()
    # html = request.form.get("html")
    # print("val=${}", val)
    # print("============================================================================")
    # print("============================================================================")
    # print("text=${}", text)
    # print("============================================================================")
    # print("============================================================================")
    # print("html=${}", html)

    return "success"


@bg.route("/label", methods=['POST', 'GET'])
def label():
    return render_template("label.html")


@bg.route("/remarkAdd", methods=['POST', 'GET'])
def remarkAdd():
    id = request.form.get('id')
    f_id = request.form.get('f_id')
    name = request.form.get('nickname')
    email = request.form.get('email')
    content = request.form.get('content')
    time = request.form.get('time')
    print(time)


@bg.route("/types/<int:type_id>", methods=['POST', 'GET'])
def types(type_id):
    type = blog_type.query.all()
    types = []
    for i in type:
        dis = {'name': i.name, 'num': len(Blog.query.filter(Blog.type_id == i.id).all()), 'id': i.id}
        types.append(dis)
    if type_id == 0:
        type_id = (blog_type.query.first()).id
    blog = Blog.query.filter(Blog.type_id == type_id).all()
    name = blog_type.query.get(type_id).name
    return render_template("types.html", type=types,bloglist = blog,url=type_id,name=name)

@bg.route("/about",methods=['POST','GET'])
def about():
    return render_template("about.html")
@bg.route("/file",methods=['POST','GET'])
def file():
    bg = Blog.query.all()
    return render_template("file.html",blog=bg)

#@bg.route("/say",methods=['POST','GET'])
#def say():
 #   saycontent=audioConvertToTxt()
  #  return saycontent
@bg.route("/say")
def say():
    saycontent=robot()
    # print(saycontent)
    return saycontent

sx_blog/templates/admin.html
{#<!DOCTYPE html>#}
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title>ONEPIECE-后台管理</title>
    <link href="{{ url_for('static',filename="images/qq.bmp") }}"  rel="icon" type="image/x-ico">
  <link rel="stylesheet" href="{{ url_for('static',filename='layui/css/layui.css') }}">
</head>
<body>
<div class="layui-layout layui-layout-admin">
  <div class="layui-header">
    <div class="layui-logo">  ONEPIECE-个人博客</div>
    <!-- 头部区域（可配合layui 已有的水平导航） -->
    <ul class="layui-nav layui-layout-left">
      <li class="layui-nav-item"><a href="">在线客服</a></li>
    </ul>
    <ul class="layui-nav layui-layout-right">
      <li class="layui-nav-item">
        <a href="javascript:;">
          <img src="{{ url_for('static',filename='images/qq.bmp') }}" class="layui-nav-img">
          管理员
        </a>
        <dl class="layui-nav-child">
          <dd><a href="">个人中心</a></dd>
          <dd><a href="">修改密码</a></dd>
        </dl>
      </li>
      <li class="layui-nav-item"><a href="javascript:exit()">退出系统</a></li>
    </ul>
  </div>

  <div class="layui-side layui-bg-black">
    <div class="layui-side-scroll">
      <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
      <ul class="layui-nav layui-nav-tree"  lay-filter="test">
        <li class="layui-nav-item layui-nav-itemed">
          <a class="" href="javascript:;"><span class="layui-icon layui-icon-template-1"></span> 文章管理</a>
          <dl class="layui-nav-child">
            <dd ><a href="/backstage/articleList" target="mainFrame"><span class="layui-icon layui-icon-read "></span> 文章列表</a></dd>
               <dd ><a href="/backstage/articleAdd" target="mainFrame"><span class="layui-icon layui-icon-edit "></span> 增加文章</a></dd>
              <dd><a href="/analysis" target="mainFrame"><span class="layui-icon layui-icon-list"></span> 统计分析</a></dd>
          </dl>
        </li>
        <li class="layui-nav-item">
          <a href="javascript:;">分类管理</a>
          <dl class="layui-nav-child">
            <dd><a href="typeList" target="mainFrame">分类列表</a></dd>
          </dl>
        </li>
{#          <li class="layui-nav-item">#}
{#          <a href="javascript:;">高校管理</a>#}
{#          <dl class="layui-nav-child">#}
{#            <dd><a href="univList" target="mainFrame">大学排名</a></dd>#}
{#            <dd><a href="javascript:;">统计分析</a></dd>#}
{#          </dl>#}
{#        </li>#}
{#        <li class="layui-nav-item"><a href="javascript:;">menu item 123</a></li>#}
{#        <li class="layui-nav-item"><a href="">the links</a></li>#}
      </ul>
    </div>
  </div>

  <div class="layui-body">
    <!-- 内容主体区域 -->
    <div style="padding: 15px;">
{#        innerframe#}
        <iframe name="mainFrame" src="/backstage/welcome"  width="100%" height="600px" frameborder="0">

        </iframe>
    </div>
  </div>

  <div class="layui-footer">
    <!-- 底部固定区域 -->
    &copy;2021-2022 Copy Right
  </div>
</div>
<script src="{{ url_for('static',filename='jquery/jquery-3.5.1.min.js') }}"></script>
<script src="{{ url_for('static',filename='layui/layui.js') }}"></script>
<script>
    function exit(){
        layer.alert("是否退出系统?",{
            closeBtn:1,
            anim:2,
            icon:1,
            btn:["确定","取消"],
            yes:function (){
                sessionStorage.clear()
                window.location.href="/"
            },
            btn2:function (){

            }
        })
    }
//JavaScript代码区域
layui.use(['element',"util"], function(){
  var element = layui.element;
  var util=layui.util
    //固定块
  util.fixbar({
    bar1: "说"
    ,bar2: false
    ,css: {right: 50, bottom: 100}
    ,bgcolor: '#FF0000'
    ,click: function(type){
      if(type === 'bar1'){
        layer.msg('您请说：')
        $.ajax({
            url:"/say",
            success:function (result){
                  layer.msg(result)
            },
            error:function (e){
                layer.msg('请求服务器失败！')
            }
        });
      } //else if(type === 'bar2') {
       // layer.msg('两个 bar 都可以设定是否开启')
     // }
    }
  });
});
</script>
</body>
</html>

sx_blog/templates/articleAdd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>高校列表</title>
{#  <link href="{{ url_for('static',filename='layui/css/layui.css') }}" rel="stylesheet">#}
    <link rel="stylesheet" href="{{ url_for('static',filename='editormd/css/editormd.css') }}"/>
    <link  href="{{ url_for('static',filename="css/bootstrap.min.css") }}" rel="stylesheet">
{#<link href="{{ url_for('static',filename="css/materialdesignicons.min.css") }}" rel="stylesheet">#}
{#<link href="{{ url_for('static',filename="css/style.min.css") }}" rel="stylesheet">#}
{#    <link rel="stylesheet" href="//res.layui.com/layui/dist/css/layui.css"  media="all">#}
</head>
<body>
 <div class="form-group">
              <label class="col-xs-2" for="example-select">选择文章分类</label>
              <div class="col-xs-3">
                <select class="form-control" id="select" name="example-select" size="1">
                  <option value="0">请选择</option>
                    {% for i in type %}
                  <option value={{ i.id }}>{{ i.name }}</option>
                    {% endfor %}
                </select>
              </div>
            </div>
<div class="form-group">
              <label class="col-xs-2" for="example-text-input">文章题目</label>
              <div class="col-xs-4">
                <input class="form-control" type="text" id="text-input" name="example-text-input" placeholder="文本..">
              </div>
            </div>
 <div class="form-group">
              <label class="col-xs-2" for="example-textarea-input">文章简介</label>
              <div class="col-xs-6">
                <textarea class="form-control" id="textarea-input" name="example-textarea-input" rows="6" placeholder="内容.."></textarea>
              </div>
            </div>
<div id="fancy-editormd" class="editormd">
    <textarea id="body" name="body" required style="display: none"></textarea>

</div>
<button onclick="tijiao()">提交</button>
<script type="text/javascript" src="{{ url_for('static',filename='jquery/jquery-3.5.1.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='layui/layui.js') }}"></script>
<script src="{{ url_for('static',filename='editormd/editormd.min.js') }}"></script>
<script type="text/html" id="toolbar">
<div class="layui-container">

</div>

</script>
<script>
$(function () {
        editormd("fancy-editormd", {
            // width: "100%", 请不要添加
            height: 640,
            syncScrolling: "single",
            path: "{{ url_for('static',filename='editormd/lib/') }}",
            saveHTMLToTextarea : true
        });
    });
  function tijiao(){
        $.ajax({
            url:"/backstage/Addarticle",
            method:"post",
            data:{
                text:$(".editormd-html-textarea").text(),
                type:$("#select").val(),
                title:$("#text-input").val(),
                describe:$("#textarea-input").val()
            },
            success:{
                {#alert( "chenggong")#}
            }

            }
        )
    }
</script>
</body>
</html>

sx_blog/templates/articleList.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>高校列表</title>
  <link href="{{ url_for('static',filename='layui/css/layui.css') }}" rel="stylesheet">
</head>
<body>
<table id="tb_info" class="layui-table"></table>
<script type="text/javascript" src="{{ url_for('static',filename='jquery/jquery-3.5.1.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='layui/layui.js') }}"></script>
<script type="text/html" id="toolbar">
<div class="layui-container">
    <a href="articleAdd" class="layui-btn layui-btn-danger"><span class="layui-icon layui-icon-addition"></span> 添加</a>
    <a href="#" class="layui-btn layui-btn-warm"><span class="layui-icon layui-icon-delete"></span> 删除</a>
    <div class="layui-input-inline">
    <input type="text" placeholder="请输入文章名称。。。" class="layui-input">
    </div>
    <a href="" class="layui-btn layui-btn-primary"><span class="layui-icon layui-icon-search"></span> 查询</a>
</div>

</script>
<script>
    layui.use(["table"], function () {
        var table = layui.table;
        var t=table.render({
            elem: "#tb_info",
            url: "/backstage/findArticleList",
            toolbar:"#toolbar",
            autoSort:true,
            limit:5,
            limits:[5,10,15,20,100],
            page:true,
            title: "大学排名信息列表",
            cols: [[
                {checkbox: true,width:100},
                {field: "id", title: "Id",align:"center",width:100},
                {field: "title", title: "文章标题",align:"center"},
                {field: "describe", title: "文章简介",align:"center"},
                {field: "creation_time", title: "创建时间",align:"center"},
                {field: "type", title: "文章分类",align:"center"},
                {field: "id", title: "操作",templet:function (d){
                    //layer.msg(d.univNameCn)
                    var str="<a href='javascript:deleteUnivById(\""+d.id+"\")'  title='删除' onclick='return confirm(\"是否真的要删除？\")'><span class='layui-icon layui-icon-delete'></span></a>"
                    var str1="<a href='javascript:deleteUnivById(\""+d.id+"\")'  title='修改' ><span class='layui-icon layui-icon-edit'></span></a>"
                    var str2="<a href='/blog/blogpage/\""+d.id+"\"'  title='查看' ><span class='layui-icon layui-icon-read'></span></a>"
                    return str+str1+str2
                    }
                }
            ]]
        });

    });
function deleteUnivById(id){
        alert(id)
        $.ajax({
            url:"/backstage/deleteUnivById",
            data:{"id":id},
            method:"post",
            success:function (result){
                if(result=="1"){
                    t.reload()
                    layer.msg("删除成功")}
                else
                    layer.msg("删除失败")
            }
        });
    }

</script>
</body>
</html>

sx_blog/templates/file.html
<!DOCTYPE html>
<html lang="en" xmlns:th="http://www.w3.org/1999/xhtml">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ONEPIECE-归档</title>

    <link href="{{ url_for('static',filename="images/qq.bmp") }}"  rel="icon" type="image/x-ico">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/semantic-ui/2.2.4/semantic.min.css">
    <link rel="stylesheet" href="{{ url_for('static',filename="css/me.css") }}">
</head>
<body>

<!--导航-->
<nav class="gird-header">
  <div class="ui container">
    <div class="ui inverted secondary stackable menu">
      <h2 class="ui olive header item" style="font-family: STSong">ONEPIECE</h2>
      <!--<div class="right m-item item m-mobile-hide">-->
        <a href="/blog/" class="m-item item m-mobile-hide" ><i class="home icon"></i>首页</a>
        <a href="types/0" class="m-item item m-mobile-hide"><i class="puzzle piece icon"></i>分类</a>
{#        <a href="#" class="m-item item m-mobile-hide"><i class="clock icon"></i>标签</a>#}
        <a href="/blog/file" class="active m-item item m-mobile-hide"><i class="clone icon"></i>归档</a>
        <a href="/blog/about" class="m-item item m-mobile-hide"><i class="book icon"></i>关于我们</a>

      <!--</div>-->
      <div class="right m-item item m-mobile-hide">
        <form name="search" action="#" method="post" target="_blank">
          <div class="ui icon transparent input m-margin-tb-tiny" style="color: white">
            <input style="color: white" type="text" name="query" placeholder="Search....">
            <i onclick="document.forms['search'].submit()" class="search link icon"></i>
          </div>
        </form>
      </div>
    </div>
  </div>
  <a href="#" class="ui menu toggle black icon button m-right-top m-mobile-show">
    <i class="sidebar icon"></i>
  </a>
</nav>


<!--顶部图片-->
<div class="m-bg-type_outer" style="width: 100%;height: 40%">
  <img src="{{ url_for('static',filename='images/typebg1.jpg') }}" alt="" class="ui m-bg image" style="width: 100%;height: 100%">
  <div class="m-bg-class_cover">
    <div class="ui container" style="position: relative ;bottom: -540px;">
      <div class="m-font-size-title m-right-bottom" align="center" style="font-family:'STXingkai'">文章归档</div>
      <div class="m-font-size-text-init-title m-margin-top" align="center">历史是什么？是过去传到将来的的回声，是将来对过去的反映</div>
    </div>
  </div>
</div>


<!--中间内容-->
<div  class="m-margin- animated fadeIn">
  <div class="ui container">
{#    <div class="ui segment m-padded-tb-large m-opacity">#}
      <div class="ui top attached padded segment m-opacity" data-v-7c3c4e45=""><div class="ui middle aligned two column grid" data-v-7c3c4e45=""><div class="column" data-v-7c3c4e45=""><h3 class="ui teal header" data-v-7c3c4e45="">归档</h3></div><div class="right aligned column" data-v-7c3c4e45=""> 共 <h2 class="ui orange header m-inline-block m-text-thin" data-v-7c3c4e45="">{{ blog|length }}</h2>篇文章 </div></div></div>
{#    </div>#}

    <div class="ui top attached teal m-opacity segment">
      <div class="ui padded vertical segment m-padded-tb-large">
        <div class="ui middle aligned mobile reversed stackable grid" >
        <h1 class="ui aligned header center">2021</h1>
            <div class="ui fluid vertical menu" >
                {% for i in blog %}
                <a href="{{ url_for('blog.blogpage',blog_id = i.id)  }}" class="item" ><span ><i class="mini teal circle icon" ></i><span>{{ i.title }}</span><div class="ui teal basic left pointing label m-padded-mini" >{{ i.creation_time }}</div></span><div class="orange ui basic left pointing label m-padded-mini" data-v-7c3c4e45="">原创</div></a>
                {% endfor %}
            </div>
        </div>
      </div>
    </div>

    <!--分页-->


  </div>
</div>

<br>
<br>
<!--底部栏-->
<footer class="ui inverted vertical segment m-padded-tb-massive m-opacity">
    <!--容器-->
    <div class="ui center aligned container" >
        <div class="ui inverted divided stackable grid">
            <div class="two wide column" style="width: 50%!important;">
                <div style="font-size: large;font-weight: bold" class="ui inverted m-text-thin m-text-spaced m-margin-top-max" >联系我</div>
                <div class="inverted link list" >
                    <div href="#" class="m-text-thin" >Email：ONEPIECElr@hotmail.com</div>
                    <div href="#" class="m-text-thin" >QQ群：447188346</div>
                </div>
            </div>

{#            <div class="four wide column" >#}
{#                <div class="ui inverted link list">#}
{#                    <div class="item">#}
{#                        <!--微信二维码-->#}
{#                        <div style="font-size: large;font-weight: bold" class="ui inverted m-text-thin m-text-spaced " >关注公众号</div>#}
{#                        <img src="../static/images/ONEPIECE.jpg" th:src="@{/images/ONEPIECE.jpg}"  class="ui m-margin-top rounded image" alt="" style="width: 110px">#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}

{#            <div class="four wide column">#}
{#                <div class="ui inverted link list">#}
{#                    <div class="item">#}
{#                        <!--微信二维码-->#}
{#                        <div style="font-size: large;font-weight: bold" class="ui inverted m-text-thin m-text-spaced " >问题交流（QQ群）</div>#}
{#                        <img src="../static/images/QQ-question.jpg" th:src="@{/images/QQ-question.jpg}"  class="ui m-margin-top rounded image" alt="" style="width: 110px">#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
            <!--博客运行时间统计-->
            <div class="two wide column" style="width: 50%!important;">
                <div style="font-size: large;font-weight: bold" class="ui inverted  m-text-thin m-text-spaced m-margin-top">客栈信息</div>
                <!--<p id="htmer_time" class="item m-text-thin"></p>-->
                <div id="blog-message">
                    <div class="ui inverted link list" style="align-content: center;margin-top: 10px">
                        <div class="m-text-thin" style="text-align: center;margin-left: 75px;">
                            文章总数： <h2 class="ui orange header m-inline-block m-margin-top-null" style="font-size:medium;"> {{ blog|length }}</h2> 篇
                        </div>
                        <div class="m-text-thin" style="text-align: center;margin-left: 75px">
                            访问总数： <h2 class="ui orange header m-inline-block m-margin-top-null" style="font-size:medium;"> 10 </h2> 次
                        </div>
                        <div class="m-text-thin" style="text-align: center;margin-left: 75px">
                            评论总数： <h2 class="ui orange header m-inline-block m-margin-top-null" style="font-size:medium;"> 0 </h2> 条
                        </div>
{#                        <div class="m-text-thin" style="text-align: left;margin-left: 75px">#}
{#                            留言总数： <h2 class="ui orange header m-inline-block m-margin-top-null" style="font-size:medium;"> 14 </h2> 条#}
{#                        </div>#}
                    </div>
                </div>
            </div>
        </div>
        <div class="ui inverted section divider"></div>
        <div style="color: #F08047;margin-top: -18px" class="ui inverted m-text-thin m-text-spaced">我的客栈已营业：<span id="htmer_time" class="item m-text-thin"></span> (*๓´╰╯`๓)</div>
        <a rel="nofollow" href="http://www.beian.miit.gov.cn" target="_blank">6514__YYDS</a>
    </div>
    </div>

</footer>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.2/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/semantic-ui/2.2.4/semantic.min.js"></script>


<script>

    // $('#newblog-container').load(/*[[@{/footer/newblog}]]*/"/footer/newblog");
    {#var test = window.location.pathname;#}
    {#var str = test.split('/')#}
    {#var id = str[str.length-1]#}
    {#alert(id)#}
    {#alert(id)#}
    {#alert($("#3").html)#}
    // 运行时间统计
    function secondToDate(second) {
        if (!second) {
            return 0;
        }
        var time = new Array(0, 0, 0, 0, 0);
        if (second >= 365 * 24 * 3600) {
            time[0] = parseInt(second / (365 * 24 * 3600));
            second %= 365 * 24 * 3600;
        }
        if (second >= 24 * 3600) {
            time[1] = parseInt(second / (24 * 3600));
            second %= 24 * 3600;
        }
        if (second >= 3600) {
            time[2] = parseInt(second / 3600);
            second %= 3600;
        }
        if (second >= 60) {
            time[3] = parseInt(second / 60);
            second %= 60;
        }
        if (second > 0) {
            time[4] = second;
        }
        return time;
    }
    function setTime() {
        /*此处为网站的创建时间*/
        var create_time = Math.round(new Date(Date.UTC(2020, 01, 25, 15, 15, 15)).getTime() / 1000);
        var timestamp = Math.round((new Date().getTime() + 8 * 60 * 60 * 1000) / 1000);
        currentTime = secondToDate((timestamp - create_time));
        currentTimeHtml = currentTime[0] + '年' + currentTime[1] + '天'
            + currentTime[2] + '时' + currentTime[3] + '分' + currentTime[4]
            + '秒';
        document.getElementById("htmer_time").innerHTML = currentTimeHtml;
    }
    setInterval(setTime, 1000);


    $('.menu.toggle').click(function () {
        $('.m-item').toggleClass('m-mobile-hide');
    });

</script>
</body>
</html>

sx_blog/templates/markdown.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>markdown</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='editormd/css/editormd.css') }}"/>
</head>
<body>
    <div id="fancy-editormd" class="editormd">
    <textarea id="body" name="body" required style="display: none"></textarea>

</div>
<button onclick="tijiao()">提交</button>
</body>

<script src="{{ url_for('static',filename='editormd/examples/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static',filename='editormd/editormd.min.js') }}"></script>
<script type="text/javascript">
    $(function () {
        editormd("fancy-editormd", {
            // width: "100%", 请不要添加
            height: 640,
            syncScrolling: "single",
            path: "{{ url_for('static',filename='editormd/lib/') }}",
            saveHTMLToTextarea : true
        });
    });
    function tijiao(){
        $.ajax({
            url:"biaodan",
            method:"post",
            data:{
                text:$(".editormd-html-textarea").text(),
                val:$(".editormd-html-textarea").val(),
                html:$(".editormd-html-textarea").html(),
            },
            success:{
                {#alert( "chenggong")#}
            }

            }
        )
    }
</script>
</html>